# Welcome to Serverless!
#

service: aws-nodejs

package:
  include:
    - iot_keys

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${env:AWS_REGION}
  profile: ${env:AWS_PROFILE}

  environment:
    API_TOKEN: ${env:API_TOKEN}
    NOTIFICATION_CHAT: ${env:NOTIFICATION_CHAT}

  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource:
         - "arn:aws:s3:::${env:PHOTO_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "iot:*"
      Resource:
        - "*"

functions:
  telegramSendPhoto:
    handler: photo.handler
    events:
      - s3:
          bucket: ${env:PHOTO_BUCKET}
          event: s3:ObjectCreated:Put

  telegramMotionActivated:
    handler: notify.motionActivated
    environment:
      MSG_MOTION_ACTIVATED: ${env:MSG_MOTION_ACTIVATED}
      IOT_HOST: ${env:IOT_HOST}
    events:
      - iot:
          sql: "SELECT * FROM 'motion-acivated'"
          enabled: true

  telegramMotionDeactivated:
    handler: notify.motionDectivated
    environment:
      MSG_MOTION_DEACTIVATED: ${env:MSG_MOTION_DEACTIVATED}
    events:
      - iot:
          sql: "SELECT * FROM 'motion-deactivated'"
          enabled: true

  telegramCommand:
    handler: command.elaborateCommand
    environment:
      ADMIN_USERNAME: ${env:ADMIN_USERNAME}
      IOT_HOST: ${env:IOT_HOST}
      MSG_NOT_A_COMMAND: ${env:MSG_NOT_A_COMMAND}
      MSG_COMMAND_NOT_FOUND: ${env:MSG_COMMAND_NOT_FOUND}
      MSG_WELCOME: ${env:MSG_WELCOME}
      MSG_ACK: ${env:MSG_ACK}
    events:
      - http:
          path: bot/update
          integration: lambda
          method: post
